# Generated by Django 6.0 on 2026-01-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelNewApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("codigo", models.CharField(max_length=20)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="registroacceso",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="modelNewApp.vehiculo",
            ),
        ),
    ]
