# Generated by Django 6.0 on 2026-01-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelNewApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="perfiles/"),
        ),
    ]
