# Generated by Django 6.0 on 2026-01-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelNewApp", "0002_persona_foto_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="debe_cambiar_password",
            field=models.BooleanField(default=True),
        ),
    ]
