# Generated by Django 6.0 on 2026-01-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelNewApp", "0002_vehiculo_registroacceso_vehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroacceso",
            name="observacion",
            field=models.CharField(
                default="Usuario olvidó marcar salida el día anterior.", max_length=100
            ),
        ),
    ]
