# Generated by Django 6.0 on 2026-01-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelNewApp", "0003_registroacceso_observacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="modelNewApp.marca"
            ),
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelNewApp.marca",
                    ),
                ),
            ],
            options={
                "unique_together": {("nombre", "marca")},
            },
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="modelNewApp.modelo"
            ),
        ),
    ]
