# Generated by Django 6.0 on 2026-01-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelNewApp", "0003_usuario_debe_cambiar_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroacceso",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="registroacceso",
            name="hora_entrada",
        ),
        migrations.RemoveField(
            model_name="registroacceso",
            name="hora_salida",
        ),
        migrations.AddField(
            model_name="registroacceso",
            name="fecha_hora_entrada",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registroacceso",
            name="fecha_hora_salida",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
