# Generated by Django 6.0 on 2026-03-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelNewApp", "0004_marca_alter_vehiculo_marca_modelo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroacceso",
            name="observacion",
            field=models.CharField(default="", max_length=100),
        ),
    ]
