# Generated by Django 6.0 on 2026-01-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modelNewApp", "0004_remove_registroacceso_fecha_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registroacceso",
            old_name="fecha_hora_entrada",
            new_name="fecha_hora",
        ),
        migrations.RemoveField(
            model_name="registroacceso",
            name="fecha_hora_salida",
        ),
        migrations.RemoveField(
            model_name="registroacceso",
            name="id_estado",
        ),
    ]
