# Generated by Django 6.0 on 2026-03-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelNewApp", "0005_alter_registroacceso_observacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroacceso",
            name="observacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
