# Generated by Django 6.0 on 2026-01-13 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "modelNewApp",
            "0005_rename_fecha_hora_entrada_registroacceso_fecha_hora_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="persona",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personas",
                to="modelNewApp.departamento",
            ),
        ),
        migrations.AddField(
            model_name="registroacceso",
            name="departamento_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros",
                to="modelNewApp.departamento",
            ),
        ),
    ]
